### ISSUE TITLE
404 Not Found with Microsoft.AspNetCore.SpaServices.Extensions

### ISSUE THREAD

**Issue by markchristianlacap** [FastEndpoints/FastEndpoints#377]
Request returns 404 when using Microsoft.AspNetCore.SpaServices.Extensions package 
Configuration works on FastEndpoints 5.7.0 but error occurs on 5.7.1

**Comment by markchristianlacap** [comment]
This is the code that I commented out to test if the Microsoft.AspNetCore.SpaServices.Extensions package is the cause of returning 404
```csharp
 app.UseSpaStaticFiles();
        app.UseSpa(x =>
        {
            if (!app.Environment.IsDevelopment())
                return;
            x.UseProxyToSpaDevelopmentServer("http://localhost:5501");
        });
```

**Comment by dj-nitehawk** [comment]
i believe changing the ordering of the middlewares should fix the issue. because in `v5.7.1`, i got rid of the custom fastendpoints middlware and sandwitched that logic into the regular endpoint middleware.

if you have trouble figuring out the right middleware order, try to comment out fastendpoints and add a test minimal api endpoint and get that working. if/when that works, fastendpoints should naturally work.

if it doesn't pls send through a self-contained/minimalistic repro project so i can debug.

**Comment by markchristianlacap** [comment]
> i believe changing the ordering of the middlewares should fix the issue. because in `v5.7.1`, i got rid of the custom fastendpoints middlware and sandwitched that logic into the regular endpoint middleware.
> 
> if you have trouble figuring out the right middleware order, try to comment out fastendpoints and add a test minimal api endpoint and get that working. if/when that works, fastendpoints should naturally work.
> 
> if it doesn't pls send through a self-contained/minimalistic repro project so i can debug.

thank you I'll play withit later thank you

**Comment by markchristianlacap** [comment]
Hi @dj-nitehawk still no luck even changing the order. Here is my sample project https://github.com/markchristianlacap/dotnet-vue-template . Thank you

**Comment by dj-nitehawk** [comment]
works like this:
```cs
var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();

var app = builder.Build();
app.UseRouting();
app.UseAuthorization();
app.UseFastEndpoints(x => x.Endpoints.RoutePrefix = "api");
app.UseEndpoints(_ => { });
if (app.Environment.IsDevelopment())
    app.UseSpa(x => x.UseProxyToSpaDevelopmentServer("http://localhost:8001"));
app.Run();
```
the reason it worked before v5.7.1 was because `UseFastEndpoints()` was a terminating middleware. it no longer is.
so now the spa proxy should be configure the same way as it would be for a regular minimal api endpoint system.
