### ISSUE TITLE
Swagger generation fails with recursion error for tree structure.

### ISSUE THREAD

**Issue by PaalCurrie** [FastEndpoints/FastEndpoints#951]
The Swagger generator fails when examining the nested objects validated by FluentValidation, as in the example code below.
The endpoint and validation rules work as expected, but when accessing the `swagger.json` file, the recursion bug is triggered.
Adding `[HideFromDocs]` to the tree node object does not work around the issue.

Encountered in versions 5.x, 6.x and 6.2.0-beta4.

Program.cs

```
using FastEndpoints;
using FastEndpoints.Swagger;

var bld = WebApplication.CreateBuilder();
bld.Services
    .AddFastEndpoints()
    .SwaggerDocument();

var app = bld.Build();
app.UseFastEndpoints()
   .UseSwaggerGen();
app.Run();
```

Endpoint.cs:

```
using FastEndpoints;
using FluentValidation;

namespace TestApp;

public class MyEndpoint : Endpoint<TreeNode, MyResponse>
{
    public override void Configure()
    {
        Post("/api/test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(TreeNode req, CancellationToken ct)
    {
        await SendAsync(new MyResponse(), cancellation: ct);
    }
}

public class MyResponse;

public class TreeNode
{
    public int Id { get; set; }
    public List<TreeNode> Children { get; set; } = [];
}

public class TreeNodeValidator : Validator<TreeNode>
{
    public TreeNodeValidator()
    {
        RuleFor(x => x.Id).GreaterThan(0).WithMessage("Id must be positive");
        RuleForEach(x => x.Children).SetValidator(this);
    }
}
```

Stack loop:
```
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyValidator(NJsonSchema.JsonSchema, FluentValidation.IValidator, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyValidationRule(NJsonSchema.JsonSchema, FluentValidation.IValidationRule, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.TryApplyValidation(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesToSchema(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.IServiceProvider)
```

**Comment by dj-nitehawk** [comment]
thanks for reporting.
fixed in `v6.2.0-beta.6`

**Comment by sdukehart-omnesoft** [comment]
I believe that I'm still seeing the same or a similar bug in 6.2.0.

```
Stack overflow.
   at System.Collections.Generic.Dictionary`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Initialize(Int32)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(Int32, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(System.Collections.Generic.IDictionary`2<System.__Canon,System.__Canon>, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at NJsonSchema.JsonSchema.get_ActualProperties()
   at NJsonSchema.JsonSchema+<>c.<get_ActualProperties>b__53_1(NJsonSchema.JsonSchema)
   at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.KeyValuePair`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Linq.Enumerable+UnionIterator`1[[System.Collections.Generic.KeyValuePair`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Linq.Enumerable.ToDictionary[[System.Collections.Generic.KeyValuePair`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.__Canon,System.__Canon>>, System.Func`2<System.Collections.Generic.KeyValuePair`2<System.__Canon,System.__Canon>,System.__Canon>, System.Func`2<System.Collections.Generic.KeyValuePair`2<System.__Canon,System.__Canon>,System.__Canon>, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at System.Linq.Enumerable.ToDictionary[[System.Collections.Generic.KeyValuePair`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.__Canon,System.__Canon>>, System.Func`2<System.Collections.Generic.KeyValuePair`2<System.__Canon,System.__Canon>,System.__Canon>, System.Func`2<System.Collections.Generic.KeyValuePair`2<System.__Canon,System.__Canon>,System.__Canon>)
   at NJsonSchema.JsonSchema.get_ActualProperties()
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesToSchema(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.TryApplyValidation(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesToSchema(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesToSchema(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.TryApplyValidation(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesToSchema(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesToSchema(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.TryApplyValidation(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesToSchema(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesToSchema(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.TryApplyValidation(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.String, System.IServiceProvider)
.
.
.
   at FastEndpoints.Swagger.ValidationSchemaProcessor.TryApplyValidation(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesToSchema(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyRulesToSchema(NJsonSchema.JsonSchema, System.Collections.ObjectModel.ReadOnlyDictionary`2<System.String,System.Collections.Generic.List`1<FluentValidation.IValidationRule>>, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.ApplyValidator(NJsonSchema.JsonSchema, FluentValidation.IValidator, System.String, System.IServiceProvider)
   at FastEndpoints.Swagger.ValidationSchemaProcessor.Process(NJsonSchema.Generation.SchemaProcessorContext)
```

**Comment by dj-nitehawk** [comment]
@sdukehart-omnesoft can you try the latest release please? does it still throw for you?
if so, please open a new issue and provide a simplified repro with just one endpoint showcasing the issue.
thanks!

**Comment by sdukehart-omnesoft** [comment]
Tried with the `7.1.0` and am still seeing the issue. I'll try to get a simplified repro put together. Thanks!
